export const REGISTER_EMAIL_REQUEST = "REGISTER_EMAIL_REQUEST";
export const REGISTER_EMAIL_SUCCESS = "REGISTER_EMAIL_SUCCESS";
export const REGISTER_EMAIL_FAILURE = "REGISTER_EMAIL_FAILURE";
export const CLEAR_EMAIL_MESSAGES = "CLEAR_EMAIL_MESSAGES";





