


// actionTypes.js

export const FETCH_GROUPS = "FETCH_GROUPS";
export const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
export const FETCH_GROUPS_FAIL = "FETCH_GROUPS_FAIL";

export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const CREATE_GROUP = "CREATE_GROUP";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAIL = "CREATE_GROUP_FAIL";
export const UPDATE_GROUP_DETAIL = "UPDATE_GROUP_DETAIL";//

export const SEND_GROUP_MESSAGE = "SEND_GROUP_MESSAGE";
export const SEND_GROUP_MESSAGE_SUCCESS = "SEND_GROUP_MESSAGE_SUCCESS";
export const SEND_GROUP_MESSAGE_FAIL = "SEND_GROUP_MESSAGE_FAIL";


// ✅ Add these new ones for EditGroup functionality:
export const FETCH_GROUP_DETAILS = "FETCH_GROUP_DETAILS";
export const FETCH_GROUP_DETAILS_SUCCESS = "FETCH_GROUP_DETAILS_SUCCESS";
export const FETCH_GROUP_DETAILS_FAIL = "FETCH_GROUP_DETAILS_FAIL";

export const EDIT_GROUP_NAME = "EDIT_GROUP_NAME";
export const EDIT_GROUP_NAME_SUCCESS = "EDIT_GROUP_NAME_SUCCESS";
export const EDIT_GROUP_NAME_FAIL = "EDIT_GROUP_NAME_FAIL";

export const ADD_MEMBER = "ADD_MEMBER";
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_FAIL = "ADD_MEMBER_FAIL";

export const REMOVE_MEMBER = "REMOVE_MEMBER";
export const REMOVE_MEMBER_SUCCESS = "REMOVE_MEMBER_SUCCESS";
export const REMOVE_MEMBER_FAIL = "REMOVE_MEMBER_FAIL";

export const MAKE_ADMIN = "MAKE_ADMIN";
export const MAKE_ADMIN_SUCCESS = "MAKE_ADMIN_SUCCESS";
export const MAKE_ADMIN_FAIL = "MAKE_ADMIN_FAIL";


